#ifndef _JEU_BLOCK_TAG_
#define _JEU_BLOCK_TAG_





/* -------------------------------------------------------------------------- */
/*                                 Enumeration                                */
/* -------------------------------------------------------------------------- */


/**
 * @struct e_blockTag
 * @brief 
 * 
 */
typedef enum {
    DEBUT_BLOCK_STRUCTURE = 999,

    // PUIT
    BLOCK_PUIT_HAUT_GAUCHE,
    BLOCK_PUIT_HAUT_CENTRE,
    BLOCK_PUIT_HAUT_DROIT,
    BLOCK_PUIT_MILIEU_GAUCHE,
    BLOCK_PUIT_MILIEU_CENTRE,
    BLOCK_PUIT_MILIEU_DROIT,
    BLOCK_PUIT_BAS_GAUCHE,
    BLOCK_PUIT_BAS_CENTRE,
    BLOCK_PUIT_BAS_DROIT,

    BLOCK_PORTE,
    BLOCK_TEMPLE_ENTREE,

    BLOCK_MUR_HAUT_GAUCHE,
    BLOCK_MUR_HAUT_CENTRE,
    BLOCK_MUR_HAUT_DROIT,
    BLOCK_MUR_GAUCHE,
    BLOCK_MUR_CENTRE,
    BLOCK_MUR_DROIT,

    BLOCK_FACADE,

    BLOCK_TOIT_PETIT_LAYER_1_1,
    BLOCK_TOIT_PETIT_LAYER_1_2,
    BLOCK_TOIT_PETIT_LAYER_1_3,
    BLOCK_TOIT_PETIT_LAYER_1_4,
    BLOCK_TOIT_PETIT_LAYER_1_5,
    BLOCK_TOIT_PETIT_LAYER_1_6,
    BLOCK_TOIT_PETIT_LAYER_2_1,
    BLOCK_TOIT_PETIT_LAYER_2_2,
    BLOCK_TOIT_PETIT_LAYER_2_3,
    BLOCK_TOIT_PETIT_LAYER_2_4,
    BLOCK_TOIT_PETIT_LAYER_2_5,
    BLOCK_TOIT_PETIT_LAYER_2_6,
    BLOCK_TOIT_PETIT_LAYER_3_1,
    BLOCK_TOIT_PETIT_LAYER_3_2,
    BLOCK_TOIT_PETIT_LAYER_3_3,
    BLOCK_TOIT_PETIT_LAYER_3_4,
    BLOCK_TOIT_PETIT_LAYER_3_5,
    BLOCK_TOIT_PETIT_LAYER_3_6,
    BLOCK_TOIT_PETIT_LAYER_4_1,
    BLOCK_TOIT_PETIT_LAYER_4_2,
    BLOCK_TOIT_PETIT_LAYER_4_3,
    BLOCK_TOIT_PETIT_LAYER_4_4,
    BLOCK_TOIT_PETIT_LAYER_4_5,
    BLOCK_TOIT_PETIT_LAYER_4_6,
    BLOCK_TOIT_PETIT_LAYER_5_1,
    BLOCK_TOIT_PETIT_LAYER_5_2,
    BLOCK_TOIT_PETIT_LAYER_5_3,
    BLOCK_TOIT_PETIT_LAYER_5_4,
    BLOCK_TOIT_PETIT_LAYER_5_5,
    BLOCK_TOIT_PETIT_LAYER_5_6,

    BLOCK_,

    FIN_BLOCK_STRUCTURE,
} e_blockTag;





#endif