/**
 * @file generation_structures.c
 * 
 * @brief Module de création des structures
 * 
 * @author Clément Hibon
 * @date 18 mars
 */





#include <stdio.h>
#include <stdlib.h>

#include "../include/structures.h"





/* -------------------------------------------------------------------------- */
/*                                  Villages                                  */
/* -------------------------------------------------------------------------- */


/**
 * @brief Tableau regroupant toutes les structures
 * 
 */
t_structure structuresPresets[] = {
    {
        STRUCTURE_PUIT,
        3, 3,
        {
            { BLOCK_PUIT_HAUT_GAUCHE, BLOCK_PUIT_HAUT_CENTRE, BLOCK_PUIT_HAUT_DROIT },
            { BLOCK_PUIT_MILIEU_GAUCHE, BLOCK_PUIT_MILIEU_CENTRE, BLOCK_PUIT_MILIEU_DROIT },
            { BLOCK_PUIT_BAS_GAUCHE, BLOCK_PUIT_BAS_CENTRE, BLOCK_PUIT_BAS_DROIT },
        }
    },


    /* ------------------------------ Petite Maison ----------------------------- */

    {
        STRUCTURE_PETITE_MAISON_1,
        7, 6,
        {
            { VIDE, BLOCK_TOIT_PETIT_LAYER_1_2_STANDARD, BLOCK_TOIT_PETIT_LAYER_1_3_STANDARD, BLOCK_TOIT_PETIT_LAYER_1_4_STANDARD, BLOCK_TOIT_PETIT_LAYER_1_5_STANDARD, VIDE },
            { BLOCK_TOIT_PETIT_LAYER_2_1_STANDARD, BLOCK_TOIT_PETIT_LAYER_2_2_STANDARD, BLOCK_TOIT_PETIT_LAYER_2_3_STANDARD, BLOCK_TOIT_PETIT_LAYER_2_4_STANDARD, BLOCK_TOIT_PETIT_LAYER_2_5_STANDARD, BLOCK_TOIT_PETIT_LAYER_2_6_STANDARD },
            { BLOCK_TOIT_PETIT_LAYER_3_1_STANDARD, BLOCK_TOIT_PETIT_LAYER_3_2_STANDARD, BLOCK_TOIT_PETIT_LAYER_3_3_STANDARD, BLOCK_TOIT_PETIT_LAYER_3_4_STANDARD, BLOCK_TOIT_PETIT_LAYER_3_5_STANDARD, BLOCK_TOIT_PETIT_LAYER_3_6_STANDARD },
            { BLOCK_TOIT_PETIT_LAYER_4_1_STANDARD, BLOCK_TOIT_PETIT_LAYER_4_2_STANDARD, BLOCK_TOIT_PETIT_LAYER_4_3_STANDARD, BLOCK_TOIT_PETIT_LAYER_4_4_STANDARD, BLOCK_TOIT_PETIT_LAYER_4_5_STANDARD, BLOCK_TOIT_PETIT_LAYER_4_6_STANDARD },
            { BLOCK_TOIT_PETIT_LAYER_5_1_STANDARD, BLOCK_TOIT_PETIT_LAYER_5_2_STANDARD, BLOCK_TOIT_PETIT_LAYER_5_3_STANDARD, BLOCK_TOIT_PETIT_LAYER_5_4_STANDARD, BLOCK_TOIT_PETIT_LAYER_5_5_STANDARD, BLOCK_TOIT_PETIT_LAYER_5_6_STANDARD },
            { BLOCK_MUR_HAUT_GAUCHE_STANDARD, BLOCK_MUR_HAUT_CENTRE_STANDARD, BLOCK_MUR_HAUT_CENTRE_STANDARD, BLOCK_MUR_HAUT_CENTRE_STANDARD, BLOCK_MUR_HAUT_CENTRE_STANDARD, BLOCK_MUR_HAUT_DROIT_STANDARD },
            { BLOCK_MUR_GAUCHE_STANDARD, BLOCK_MUR_CENTRE_STANDARD, BLOCK_MUR_CENTRE_STANDARD, BLOCK_PORTE, BLOCK_MUR_CENTRE_STANDARD, BLOCK_MUR_DROIT_STANDARD },
        },
    },
    {
        STRUCTURE_PETITE_MAISON_2,
        7, 6,
        {
            { VIDE, BLOCK_TOIT_PETIT_LAYER_1_2_ROUGE, BLOCK_TOIT_PETIT_LAYER_1_3_ROUGE, BLOCK_TOIT_PETIT_LAYER_1_4_ROUGE, BLOCK_TOIT_PETIT_LAYER_1_5_ROUGE, VIDE },
            { BLOCK_TOIT_PETIT_LAYER_2_1_ROUGE, BLOCK_TOIT_PETIT_LAYER_2_2_ROUGE, BLOCK_TOIT_PETIT_LAYER_2_3_ROUGE, BLOCK_TOIT_PETIT_LAYER_2_4_ROUGE, BLOCK_TOIT_PETIT_LAYER_2_5_ROUGE, BLOCK_TOIT_PETIT_LAYER_2_6_ROUGE },
            { BLOCK_TOIT_PETIT_LAYER_3_1_ROUGE, BLOCK_TOIT_PETIT_LAYER_3_2_ROUGE, BLOCK_TOIT_PETIT_LAYER_3_3_ROUGE, BLOCK_TOIT_PETIT_LAYER_3_4_ROUGE, BLOCK_TOIT_PETIT_LAYER_3_5_ROUGE, BLOCK_TOIT_PETIT_LAYER_3_6_ROUGE },
            { BLOCK_TOIT_PETIT_LAYER_4_1_ROUGE, BLOCK_TOIT_PETIT_LAYER_4_2_ROUGE, BLOCK_TOIT_PETIT_LAYER_4_3_ROUGE, BLOCK_TOIT_PETIT_LAYER_4_4_ROUGE, BLOCK_TOIT_PETIT_LAYER_4_5_ROUGE, BLOCK_TOIT_PETIT_LAYER_4_6_ROUGE },
            { BLOCK_TOIT_PETIT_LAYER_5_1_ROUGE, BLOCK_TOIT_PETIT_LAYER_5_2_ROUGE, BLOCK_TOIT_PETIT_LAYER_5_3_ROUGE, BLOCK_TOIT_PETIT_LAYER_5_4_ROUGE, BLOCK_TOIT_PETIT_LAYER_5_5_ROUGE, BLOCK_TOIT_PETIT_LAYER_5_6_ROUGE },
            { BLOCK_MUR_HAUT_GAUCHE_ROUGE, BLOCK_MUR_HAUT_CENTRE_ROUGE, BLOCK_MUR_HAUT_CENTRE_ROUGE, BLOCK_MUR_HAUT_CENTRE_ROUGE, BLOCK_MUR_HAUT_CENTRE_ROUGE, BLOCK_MUR_HAUT_DROIT_ROUGE },
            { BLOCK_MUR_GAUCHE_ROUGE, BLOCK_MUR_CENTRE_ROUGE, BLOCK_MUR_CENTRE_ROUGE, BLOCK_PORTE, BLOCK_MUR_CENTRE_ROUGE, BLOCK_MUR_DROIT_ROUGE },
        },
    },
    {
        STRUCTURE_PETITE_MAISON_3,
        7, 6,
        {
            { VIDE, BLOCK_TOIT_PETIT_LAYER_1_2_BLEU, BLOCK_TOIT_PETIT_LAYER_1_3_BLEU, BLOCK_TOIT_PETIT_LAYER_1_4_BLEU, BLOCK_TOIT_PETIT_LAYER_1_5_BLEU, VIDE },
            { BLOCK_TOIT_PETIT_LAYER_2_1_BLEU, BLOCK_TOIT_PETIT_LAYER_2_2_BLEU, BLOCK_TOIT_PETIT_LAYER_2_3_BLEU, BLOCK_TOIT_PETIT_LAYER_2_4_BLEU, BLOCK_TOIT_PETIT_LAYER_2_5_BLEU, BLOCK_TOIT_PETIT_LAYER_2_6_BLEU },
            { BLOCK_TOIT_PETIT_LAYER_3_1_BLEU, BLOCK_TOIT_PETIT_LAYER_3_2_BLEU, BLOCK_TOIT_PETIT_LAYER_3_3_BLEU, BLOCK_TOIT_PETIT_LAYER_3_4_BLEU, BLOCK_TOIT_PETIT_LAYER_3_5_BLEU, BLOCK_TOIT_PETIT_LAYER_3_6_BLEU },
            { BLOCK_TOIT_PETIT_LAYER_4_1_BLEU, BLOCK_TOIT_PETIT_LAYER_4_2_BLEU, BLOCK_TOIT_PETIT_LAYER_4_3_BLEU, BLOCK_TOIT_PETIT_LAYER_4_4_BLEU, BLOCK_TOIT_PETIT_LAYER_4_5_BLEU, BLOCK_TOIT_PETIT_LAYER_4_6_BLEU },
            { BLOCK_TOIT_PETIT_LAYER_5_1_BLEU, BLOCK_TOIT_PETIT_LAYER_5_2_BLEU, BLOCK_TOIT_PETIT_LAYER_5_3_BLEU, BLOCK_TOIT_PETIT_LAYER_5_4_BLEU, BLOCK_TOIT_PETIT_LAYER_5_5_BLEU, BLOCK_TOIT_PETIT_LAYER_5_6_BLEU },
            { BLOCK_MUR_HAUT_GAUCHE_BLEU, BLOCK_MUR_HAUT_CENTRE_BLEU, BLOCK_MUR_HAUT_CENTRE_BLEU, BLOCK_MUR_HAUT_CENTRE_BLEU, BLOCK_MUR_HAUT_CENTRE_BLEU, BLOCK_MUR_HAUT_DROIT_BLEU },
            { BLOCK_MUR_GAUCHE_BLEU, BLOCK_MUR_CENTRE_BLEU, BLOCK_MUR_CENTRE_BLEU, BLOCK_PORTE, BLOCK_MUR_CENTRE_BLEU, BLOCK_MUR_DROIT_BLEU },
        },
    },



    /* ------------------------------ Grande Maison ----------------------------- */

    {
        STRUCTURE_GRANDE_MAISON_1,
        8, 6,
        {
            { VIDE, BLOCK_TOIT_PETIT_LAYER_1_2_STANDARD, BLOCK_TOIT_PETIT_LAYER_1_3_STANDARD, BLOCK_TOIT_PETIT_LAYER_1_4_STANDARD, BLOCK_TOIT_PETIT_LAYER_1_5_STANDARD, VIDE },
            { BLOCK_TOIT_PETIT_LAYER_2_1_STANDARD, BLOCK_TOIT_PETIT_LAYER_2_2_STANDARD, BLOCK_TOIT_PETIT_LAYER_2_3_STANDARD, BLOCK_TOIT_PETIT_LAYER_2_4_STANDARD, BLOCK_TOIT_PETIT_LAYER_2_5_STANDARD, BLOCK_TOIT_PETIT_LAYER_2_6_STANDARD },
            { BLOCK_TOIT_PETIT_LAYER_3_1_STANDARD, BLOCK_TOIT_PETIT_LAYER_3_2_STANDARD, BLOCK_TOIT_PETIT_LAYER_3_3_STANDARD, BLOCK_TOIT_PETIT_LAYER_3_4_STANDARD, BLOCK_TOIT_PETIT_LAYER_3_5_STANDARD, BLOCK_TOIT_PETIT_LAYER_3_6_STANDARD },
            { BLOCK_TOIT_PETIT_LAYER_4_1_STANDARD, BLOCK_TOIT_PETIT_LAYER_4_2_STANDARD, BLOCK_TOIT_PETIT_LAYER_4_3_STANDARD, BLOCK_TOIT_PETIT_LAYER_4_4_STANDARD, BLOCK_TOIT_PETIT_LAYER_4_5_STANDARD, BLOCK_TOIT_PETIT_LAYER_4_6_STANDARD },
            { BLOCK_TOIT_PETIT_LAYER_5_1_STANDARD, BLOCK_TOIT_PETIT_LAYER_5_2_STANDARD, BLOCK_TOIT_PETIT_LAYER_5_3_STANDARD, BLOCK_TOIT_PETIT_LAYER_5_4_STANDARD, BLOCK_TOIT_PETIT_LAYER_5_5_STANDARD, BLOCK_TOIT_PETIT_LAYER_5_6_STANDARD },
            { BLOCK_MUR_HAUT_GAUCHE_STANDARD, BLOCK_MUR_HAUT_CENTRE_STANDARD, BLOCK_MUR_HAUT_CENTRE_STANDARD, BLOCK_MUR_HAUT_CENTRE_STANDARD, BLOCK_MUR_HAUT_CENTRE_STANDARD, BLOCK_MUR_HAUT_DROIT_STANDARD },
            { BLOCK_MUR_GAUCHE_STANDARD, BLOCK_MUR_CENTRE_STANDARD, BLOCK_PORTE, BLOCK_PORTE, BLOCK_MUR_CENTRE_STANDARD, BLOCK_MUR_DROIT_STANDARD },
        },
    },
    {
        STRUCTURE_GRANDE_MAISON_2,
        8, 6,
        {
            { VIDE, BLOCK_TOIT_PETIT_LAYER_1_2_ROUGE, BLOCK_TOIT_PETIT_LAYER_1_3_ROUGE, BLOCK_TOIT_PETIT_LAYER_1_4_ROUGE, BLOCK_TOIT_PETIT_LAYER_1_5_ROUGE, VIDE },
            { BLOCK_TOIT_PETIT_LAYER_2_1_ROUGE, BLOCK_TOIT_PETIT_LAYER_2_2_ROUGE, BLOCK_TOIT_PETIT_LAYER_2_3_ROUGE, BLOCK_TOIT_PETIT_LAYER_2_4_ROUGE, BLOCK_TOIT_PETIT_LAYER_2_5_ROUGE, BLOCK_TOIT_PETIT_LAYER_2_6_ROUGE },
            { BLOCK_TOIT_PETIT_LAYER_3_1_ROUGE, BLOCK_TOIT_PETIT_LAYER_3_2_ROUGE, BLOCK_TOIT_PETIT_LAYER_3_3_ROUGE, BLOCK_TOIT_PETIT_LAYER_3_4_ROUGE, BLOCK_TOIT_PETIT_LAYER_3_5_ROUGE, BLOCK_TOIT_PETIT_LAYER_3_6_ROUGE },
            { BLOCK_TOIT_PETIT_LAYER_4_1_ROUGE, BLOCK_TOIT_PETIT_LAYER_4_2_ROUGE, BLOCK_TOIT_PETIT_LAYER_4_3_ROUGE, BLOCK_TOIT_PETIT_LAYER_4_4_ROUGE, BLOCK_TOIT_PETIT_LAYER_4_5_ROUGE, BLOCK_TOIT_PETIT_LAYER_4_6_ROUGE },
            { BLOCK_TOIT_PETIT_LAYER_5_1_ROUGE, BLOCK_TOIT_PETIT_LAYER_5_2_ROUGE, BLOCK_TOIT_PETIT_LAYER_5_3_ROUGE, BLOCK_TOIT_PETIT_LAYER_5_4_ROUGE, BLOCK_TOIT_PETIT_LAYER_5_5_ROUGE, BLOCK_TOIT_PETIT_LAYER_5_6_ROUGE },
            { BLOCK_MUR_HAUT_GAUCHE_ROUGE, BLOCK_MUR_HAUT_CENTRE_ROUGE, BLOCK_MUR_HAUT_CENTRE_ROUGE, BLOCK_MUR_HAUT_CENTRE_ROUGE, BLOCK_MUR_HAUT_CENTRE_ROUGE, BLOCK_MUR_HAUT_DROIT_ROUGE },
            { BLOCK_MUR_GAUCHE_ROUGE, BLOCK_MUR_CENTRE_ROUGE, BLOCK_PORTE, BLOCK_PORTE, BLOCK_MUR_CENTRE_ROUGE, BLOCK_MUR_DROIT_ROUGE },
        },
    },
    {
        STRUCTURE_GRANDE_MAISON_3,
        8, 6,
        {
            { VIDE, BLOCK_TOIT_PETIT_LAYER_1_2_BLEU, BLOCK_TOIT_PETIT_LAYER_1_3_BLEU, BLOCK_TOIT_PETIT_LAYER_1_4_BLEU, BLOCK_TOIT_PETIT_LAYER_1_5_BLEU, VIDE },
            { BLOCK_TOIT_PETIT_LAYER_2_1_BLEU, BLOCK_TOIT_PETIT_LAYER_2_2_BLEU, BLOCK_TOIT_PETIT_LAYER_2_3_BLEU, BLOCK_TOIT_PETIT_LAYER_2_4_BLEU, BLOCK_TOIT_PETIT_LAYER_2_5_BLEU, BLOCK_TOIT_PETIT_LAYER_2_6_BLEU },
            { BLOCK_TOIT_PETIT_LAYER_3_1_BLEU, BLOCK_TOIT_PETIT_LAYER_3_2_BLEU, BLOCK_TOIT_PETIT_LAYER_3_3_BLEU, BLOCK_TOIT_PETIT_LAYER_3_4_BLEU, BLOCK_TOIT_PETIT_LAYER_3_5_BLEU, BLOCK_TOIT_PETIT_LAYER_3_6_BLEU },
            { BLOCK_TOIT_PETIT_LAYER_4_1_BLEU, BLOCK_TOIT_PETIT_LAYER_4_2_BLEU, BLOCK_TOIT_PETIT_LAYER_4_3_BLEU, BLOCK_TOIT_PETIT_LAYER_4_4_BLEU, BLOCK_TOIT_PETIT_LAYER_4_5_BLEU, BLOCK_TOIT_PETIT_LAYER_4_6_BLEU },
            { BLOCK_TOIT_PETIT_LAYER_5_1_BLEU, BLOCK_TOIT_PETIT_LAYER_5_2_BLEU, BLOCK_TOIT_PETIT_LAYER_5_3_BLEU, BLOCK_TOIT_PETIT_LAYER_5_4_BLEU, BLOCK_TOIT_PETIT_LAYER_5_5_BLEU, BLOCK_TOIT_PETIT_LAYER_5_6_BLEU },
            { BLOCK_MUR_HAUT_GAUCHE_BLEU, BLOCK_MUR_HAUT_CENTRE_BLEU, BLOCK_MUR_HAUT_CENTRE_BLEU, BLOCK_MUR_HAUT_CENTRE_BLEU, BLOCK_MUR_HAUT_CENTRE_BLEU, BLOCK_MUR_HAUT_DROIT_BLEU },
            { BLOCK_MUR_GAUCHE_BLEU, BLOCK_MUR_CENTRE_BLEU, BLOCK_PORTE, BLOCK_PORTE, BLOCK_MUR_CENTRE_BLEU, BLOCK_MUR_DROIT_BLEU },
        },
    },


    /* --------------------------------- Temple --------------------------------- */

    {
        STRUCTURE_ENTREE_TEMPLE,
        2, 3,
        {
            { BLOCK_TEMPLE_ENTREE_HAUT_GAUCHE, BLOCK_TEMPLE_ENTREE_HAUT_CENTRE, BLOCK_TEMPLE_ENTREE_HAUT_DROIT },
            { BLOCK_TEMPLE_ENTREE_BAS_GAUCHE, BLOCK_TEMPLE_ENTREE_BAS_CENTRE, BLOCK_TEMPLE_ENTREE_BAS_DROIT },
        }
    },
};





/* -------------------------------------------------------------------------- */
/*                                 Generation                                 */
/* -------------------------------------------------------------------------- */


/**
 * @brief Permet de génèrer une structure demandé
 * 
 * @param position La position où est générée la structure
 * @param tag Le tag de la structure
 * @param map La map dans laquelle est générée la structure
 */
void genererStructure(const t_vecteur2 position, const e_structureTag tag, t_map *map) {
    t_block *block = NULL;

    t_structure structure = structuresPresets[tag];
    
    
    for (int y = position.y, h = 0; y < position.y + structure.hauteur; y++, h++) {
        for (int x = position.x, L = 0; x < position.x + structure.largeur; x++, L++) {
            e_blockTag blockStructure = structure.blocks[h][L];

            block = getBlockDansMap(x, y, COUCHE_OBJETS, map);
            block->tag = blockStructure;
        }
    }
}
